### ISSUE TITLE
low resolution on startup

### ISSUE THREAD

**Issue by tayza-mm** [info-beamer/package-hd-player#2]
Hi,
I have a issue when i dont plug in HDMI cable player only output 640 resolution from Pi.
anyway to fix at 1080p?

**Comment by dividuum** [comment]
https://info-beamer.com/doc/device-configuration#forceoutputresolution

**Comment by tayza-mm** [comment]
Thanks but i have not idea how to edit config file.
can you show me how?

**Comment by dividuum** [comment]
The easiest way, if you don't want to manually edit/create the `config/tvservice` file on the SD card of your Pi is to go to the device page for your Pi, click on the red "Manage" button and then select "activate testing channel" and confirm. The device will upgrade the the next release of info-beamer, which is currently still in development. One of the new features is an editor that allows you to change such configuration values on the web interface. After the device rebooted, reload the device page and a bit down you'll see the configuration editor. There's a tab for editing the resolution. Click save and the setting will be activated after a reboot.

**Comment by tayza-mm** [comment]
Correct me if i'm wrong.
In SD card,
1. Create tvservice.txt in "config" folder
2. Type below codes in tvservice.txt file. 
# Force the monitor to HDMI mode so that sound will be sent over HDMI cable
hdmi_drive=2
# Set monitor mode to DMT
hdmi_group=2
# Set monitor resolution to 1920x1080 FHD 60Hz (HDMI_DMT_XGA_60)
hdmi_mode=87
# Make display smaller to stop text spilling off the screen
overscan_left=20
overscan_right=12
overscan_top=10
overscan_bottom=10

3. save file

**Comment by dividuum** [comment]
No. The file is `/config/tvservice`, not `/config/tvservice.txt`. And you can only specify the resolution option in there. If you want to set arbitrary options like the ones you have, you'll have to place them in `/config/userconfig.txt`. See [here](https://info-beamer.com/doc/device-configuration#customraspberrypisettings).

**Comment by tayza-mm** [comment]
i see. let me try. Thanks.
