### ISSUE TITLE
Audio Not playing on Raspberry pi zero

### ISSUE THREAD

**Issue by lothma** [info-beamer/package-hd-player#3]
Hi I have enabled the "play audio for videos" option but I'm not having any luck hearing the audio, I have the Raspberry Pi Zero connected to a TV thru HDMI cable that supports audio play back can you please help me with this issue?

**Comment by dividuum** [comment]
You need to configure how your Pi should output audio: See https://info-beamer.com/doc/device-configuration#specifyaudiotarget

If you have the newest OS version installed on the Pi, you can also change that setting from the device page using the configuration editor.
