### ISSUE TITLE
Feature request: mass assign play time for images

### ISSUE THREAD

**Issue by acamann** [info-beamer/package-hd-player#5]
It would be helpful to be able to mass assign the play time (in seconds) for all images being displayed.  Currently you can change the value for each individual image and it is defaulted to 5 seconds.

**Comment by dividuum** [comment]
You could use the API for that for now. Or fork the package, set a new default and import that package into your account. In the future, I might look into adding a feature to change multiple items in a [list option field (like that playlist)](https://info-beamer.com/doc/package-reference#optionlist) at once.
